# Generated by Django 5.2.2 on 2025-08-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='Hello', editable=False, max_length=200, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
