# Generated by Django 5.2.2 on 2025-08-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(editable=False, max_length=200, unique=True, verbose_name='Слаг'),
        ),
    ]
