# Generated by Django 5.2.2 on 2025-09-13 08:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed_users',
            field=models.ManyToManyField(related_name='viewed_posts', to=settings.AUTH_USER_MODEL, verbose_name='Просмотрено пользователями'),
        ),
    ]
